version: '3.0'

volumes:
  mongodbvol:

services:
  mongodb:
    container_name: mongodb
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    image: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodbvol:/data/db

  python-docker:
    container_name: python-docker
    build:
      context: .
      dockerfile: Dockerfile-python
    image: python-docker
    ports:
      - "5000:5000"
    links:
      - mongodb:mongodb
    environment:
      MONGODB_URL: mongodb://mongodb:27017/teamlion

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    image: app
    ports:
      - "8080:8080"
    links:
      - mongodb:mongodb
      - python-docker:python-docker