FROM maven:3.6.3-jdk-11 AS BUILD
COPY /teamlion/src /teamlion/src
COPY /teamlion/pom.xml /teamlion/pom.xml
WORKDIR /
RUN mvn -f /teamlion/pom.xml clean package

FROM openjdk:11
COPY --from=BUILD /teamlion/target/teamlion-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]